### PR TITLE
Add secret scan CI

### PR DESCRIPTION
**Pull request by TravisEz13**
## PR Summary

Add a CI YAML that will scan for secrets.
This will prevents secrets from accidentally being added to the repo.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `Dockerfile`, `.sh`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **Adds a new image or tag**
  - [x] Not Applicable
- **OR**
  - [ ] Update [README.powershellcommunity.md](https://github.com/PowerShell/PowerShell-Docker/blob/master/assets/README.powershellcommunity.md)
  - [ ] Update [vsts-ci.yml](https://github.com/PowerShell/PowerShell-Docker/blob/master/vsts-ci.yml)

### CODE REVIEW

**Comment by TravisEz13** [comment]
@PoshChan 	Please remind me in 24 hours

**Comment by PoshChan** [comment]
@TravisEz13,
all requests start with the magic word: Please.

**Comment by RDIL** [comment]
What is that gif 🤦🏻‍♂️

**Comment by TravisEz13** [comment]
Ask Steve... I think emoji's are okay, but gifs are not nice in github as a bot reply.

**Comment by SteveL-MSFT** [comment]
That gif is from [Jurassic Park](https://www.youtube.com/watch?v=RfiQYRn7fBg).  Maybe I'll make it an option in settings...

Added some tracing on the backend to see why it's not picking up your 'please'.

**Comment by RDIL** [comment]
@PoshChan please remind me in 1h

**Comment by PoshChan** [comment]
@RDIL, I do not understand: please remind me in 1h

**Pull request merged**
