### PR TITLE
Updated ArchLinux

### PR DESCRIPTION
**Pull request by kiazhi**
## PR Summary

Returning this image from unstable to community-stable.

- Fixed ArchLinux Image and PowerShell version

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `Dockerfile`, `.sh`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **Adds a new image or tag**
  - [x] Not Applicable
- **OR**
  - [ ] Update [README.powershellcommunity.md](https://github.com/PowerShell/PowerShell-Docker/blob/master/assets/README.powershellcommunity.md)
  - [ ] Update [vsts-ci.yml](https://github.com/PowerShell/PowerShell-Docker/blob/master/vsts-ci.yml)

### CODE REVIEW

**Comment by kiazhi** [comment]
Hi @RDIL @TravisEz13 

What's wrong with the `build.ps1` script throwing errors?

https://dev.azure.com/powershell/docker/_build/results?buildId=53939&view=logs&j=1117a397-4ba5-51f0-cbe9-3803dbf0f9f0&t=78b851a4-caa5-5ed7-5f28-a3aaa94d997e&l=19

All image build having issue. What had changed?

**Comment by RDIL** [comment]
Huh, I've never seen it do that before.  Lets see if this is just a one-time error

**Comment by RDIL** [comment]
@PoshChan please rerun CI

**Comment by PoshChan** [comment]
@RDIL, successfully started rebuild of `docker-PR`

**Comment by RDIL** [comment]
@TravisEz13 I have no idea what's going on here, any thoughts?

**Comment by TravisEz13** [comment]
I don't have permissions to update the branch.

**Comment by TravisEz13** [comment]
Troubleshooting here: https://github.com/PowerShell/PowerShell-Docker/pull/431

**Comment by TravisEz13** [comment]
Pester 5 was released and it is forcing the test script blocks to run in strict mode...

**Comment by TravisEz13** [comment]
@kiazhi Thanks again for your contribution.

**Comment by kiazhi** [comment]
I wasn't expecting Pester5 to have a breaking change to this repo. 🤔

Thanks for resolving, team. @TravisEz13 @SteveL-MSFT

**Pull request merged**
