### PR TITLE
Changed fulltags for nanoserver lts and stable

### PR DESCRIPTION
**Pull request by anamnavi**
## PR Summary

changing windows nanoserver lts and stable images to use generated full tag, and not set the full tag dynamically. Thus, a dockerfile is created for each nanoserver's version (1809, 1903, 1909, 2004).

## PR Checklist

- [x ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [x ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x ] [Make sure all `Dockerfile`, `.sh`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **Adds a new image or tag**
will update tag for existing lts: nanoserver1809, nanoserver1903, nanoserver1909, nanoserver2004 images and stable: nanoserver1809, nanoserver1903, nanoserver1909, nanoserver2004 images.
  - [ ] Not Applicable
- **OR**
  - [ ] Update [README.powershellcommunity.md](https://github.com/PowerShell/PowerShell-Docker/blob/master/docs/README.powershellcommunity.md)
  - [ ] Update [vsts-ci.yml](https://github.com/PowerShell/PowerShell-Docker/blob/master/vsts-ci.yml)

### CODE REVIEW

**Review by RDIL — APPROVED** [review]

**Comment by TravisEz13** [comment]
ACR CI didn't run your changes.  I updated the YAML to run them.

**Comment by anamnavi** [comment]
thanks for making that change, the tests passed with my changes being run now @TravisEz13

**Review by TravisEz13 — CHANGES_REQUESTED** [review]

**Review by TravisEz13 — APPROVED** [review]

**Pull request merged**
