### PR TITLE
Add NTLM remoting to archlinux

### PR DESCRIPTION
**Pull request by RDIL**
## PR Summary
#124 support
waiting on #281 

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `Dockerfile`, `.sh`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **Adds a new image or tag**
  - [ ] Not Applicable
- **OR**
  - [ ] Update [README.powershellcommunity.md](https://github.com/PowerShell/PowerShell-Docker/blob/master/assets/README.powershellcommunity.md)
  - [ ] Update [vsts-ci.yml](https://github.com/PowerShell/PowerShell-Docker/blob/master/vsts-ci.yml)

### CODE REVIEW

**Comment by TravisEz13** [comment]
@PoshChan Please remind me in 1 hour

**Comment by PoshChan** [comment]
@TravisEz13, this is the reminder you requested 1 hour ago

**Comment by RDIL** [comment]
Looks like its been pulled from the repo, I'm going to build it (I've cloned it into a GH repo [here](https://github.com/RDIL/gss-ntlmssp)) locally and push it to the archlinux package repo under a different name, like libntlm-pwsh to avoid future conflicts

**Comment by TravisEz13** [comment]
@RDIL If this is not maintained, let's not include it.

**Comment by RDIL** [comment]
Its not really that its unmaintained, its that I can't seem to find out why it isn't finding the package

**Comment by kiazhi** [comment]
> Its not really that its unmaintained, its that I can't seem to find out why it isn't finding the package

I agreed with @RDIL that its just not available through `pacman` package manager.

The official package repository is [here](https://aur.archlinux.org/packages/gss-ntlmssp/) but it seems like we will need to use `git clone https://aur.archlinux.org/gss-ntlmssp.git`  and make the package.

I working on a workaround solution to this issue by using multi-stage builds Dockerfile. I will submit a PR later.

**Comment by RDIL** [comment]
Duplicate of #291

**Pull request closed without merging**
