### PR TITLE
Updated ParrotSec

### LINKED ISSUE #289: ParrotSec is failing
ParrotSec/Parrot container image building is failing.

### PR DESCRIPTION
**Pull request by kiazhi**
## PR Summary

- fixes #289 
- includes update of ParrotSec/Core Image and PowerShell version

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `Dockerfile`, `.sh`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **Adds a new image or tag**
  - [ ] Not Applicable
- **OR**
  - [ ] Update [README.powershellcommunity.md](https://github.com/PowerShell/PowerShell-Docker/blob/master/assets/README.powershellcommunity.md)
  - [ ] Update [vsts-ci.yml](https://github.com/PowerShell/PowerShell-Docker/blob/master/vsts-ci.yml)

### CODE REVIEW

**Comment by kiazhi** [comment]
@TravisEz13, @RDIL - Great work on the restructuring... Took me about an hour to figure out why it doesn't generate the MatrixJson to be included in the pipeline. Very cool work. I'm impressed.

**Comment by TravisEz13** [comment]
Fixed test about image size.

**Comment by TravisEz13** [comment]
@PoshChan  Please remind me in 1 hour.

**Comment by TravisEz13** [comment]
Updated to use the simpler floating tag pattern.

**Comment by PoshChan** [comment]
@TravisEz13, this is the reminder you requested 1 hour. ago

**Comment by TravisEz13** [comment]
Thanks @kiazhi !

**Pull request merged**
