### PR TITLE
I think I fixed parrot

### PR DESCRIPTION
**Pull request by RDIL**
## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `Dockerfile`, `.sh`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **Adds a new image or tag**
  - [ ] Not Applicable
- **OR**
  - [ ] Update [README.powershellcommunity.md](https://github.com/PowerShell/PowerShell-Docker/blob/master/assets/README.powershellcommunity.md)
  - [ ] Update [vsts-ci.yml](https://github.com/PowerShell/PowerShell-Docker/blob/master/vsts-ci.yml)

### CODE REVIEW

**Comment by TravisEz13** [comment]
How to find the logs from the CI system:

image
image
image

**Comment by RDIL** [comment]
Ah I see.

**Comment by TravisEz13** [comment]
Azure DevOps could make the UI simpler...

**Comment by RDIL** [comment]
Yes.

**Comment by RDIL** [comment]
Okay @TravisEz13 it looks like I got the docker image for parrot to build, but the pester tests are failing.

**Comment by TravisEz13** [comment]
It's still failing: https://powershell.visualstudio.com/docker/_build/results?buildId=32912&view=logs&jobId=cacae5f1-16bd-573b-2b25-dc38a6af142a&taskId=c47bca0f-1af9-5d80-5180-73bd7733cd66&lineStart=62&lineEnd=63&colStart=1&colEnd=1

**Pull request closed without merging**
