### PR TITLE
Fix ArchLinux image: Dockerfile COPY failed with no such file or directory for gss-ntlmssp package file

### PR DESCRIPTION
**Pull request by kiazhi**
## PR Summary

Fix `makepkg` auto generated gss-ntlmssp package filename due to source repository has a version upgrade to `gss-ntlmssp-0.9.0-2-x86_64.pkg.tar.zst`. This has been rectify by renaming packaged package filename to generic `gss-ntlmssp.pkg.tar.zst` package filename for Dockerfile `COPY` arguments.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [X] [Make sure all `Dockerfile`, `.sh`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **Adds a new image or tag**
  - [ ] Not Applicable
- **OR**
  - [ ] Update [README.powershellcommunity.md](https://github.com/PowerShell/PowerShell-Docker/blob/master/docs/README.powershellcommunity.md)
  - [ ] Update [vsts-ci.yml](https://github.com/PowerShell/PowerShell-Docker/blob/master/vsts-ci.yml)

### CODE REVIEW

**Comment by RDIL** [comment]
Duplicate of #507

**Comment by kiazhi** [comment]
Hi @RDIL ,
This PR #506 is to fix ArchLinux distro and PR #507 is to fix BlackArch distro that is using ArchLinux distro as base platform. Its not really duplication, the files and folders are different too.

**Comment by RDIL** [comment]
Whoops, I didn't notice that!  My bad.

**Review by RDIL — APPROVED** [review]

**Comment by kiazhi** [comment]
@PoshChan please rerun CI

**Comment by PoshChan** [comment]
@kiazhi, successfully started rebuild of `docker-PR`

**Review by TravisEz13 — APPROVED** [review]

**Pull request merged**
