### PR TITLE
Fix GitPod

### PR DESCRIPTION
**Pull request by TravisEz13**
## PR Summary

Fix GitPod
cc @RDIL , FYI I messaged you on twitter.
Did you get the PowerShell or Docker extension working?

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `Dockerfile`, `.sh`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **Adds a new image or tag**
  - [ ] Not Applicable
- **OR**
  - [ ] Update [README.powershellcommunity.md](https://github.com/PowerShell/PowerShell-Docker/blob/master/assets/README.powershellcommunity.md)
  - [ ] Update [vsts-ci.yml](https://github.com/PowerShell/PowerShell-Docker/blob/master/vsts-ci.yml)

### CODE REVIEW

**Comment by RDIL** [comment]
I'll fix the extensions

**Comment by TravisEz13** [comment]
I don't think PowerShell will work.  It looks like GitPod assume sockets, but the extension uses named pipes.

**Comment by TravisEz13** [comment]
@RDIL I'll merge this in the mean time?

**Comment by RDIL** [comment]
Works for me with this in YAML:

```yaml
vscode:
  extensions:
    - ms-vscode.powershell@2019.9.0:q6zCSsv80QQcQx+xWgPFRA==
````

**Comment by TravisEz13** [comment]
Does this ever start?
image

**Comment by RDIL** [comment]
Ready for merge as is

**Pull request merged**
