### PR TITLE
Add module cache analysis to Windows Images

### PR DESCRIPTION
**Pull request by TravisEz13**
## PR Summary

Add module cache analysis to Windows Images

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `Dockerfile`, `.sh`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **Adds a new image or tag**
  - [x] Not Applicable
- **OR**
  - [ ] Update [README.powershellcommunity.md](https://github.com/PowerShell/PowerShell-Docker/blob/master/assets/README.powershellcommunity.md)
  - [ ] Update [vsts-ci.yml](https://github.com/PowerShell/PowerShell-Docker/blob/master/vsts-ci.yml)

### CODE REVIEW

**Comment by TravisEz13** [comment]
cc @kiazhi 	I finally got the module analysis cache creation working for windows.  Would you mind reviewing?

**Comment by kiazhi** [comment]
Those codes LGTM @TravisEz13 

I understood that PowerShell obtains the path from an environment variable and the path can be anything. 

Personally, I'm just not 100% sure if the path should be defined with `C:\PSModuleAnalysisCache\ModuleAnalysisCache` as default in those container image because it does not align to [Microsoft Docs](
https://docs.microsoft.com/en-us/powershell/wmf/5.1/scenarios-features#module-analysis-cache).

Unless you are prepared to update/add documentation about PSModuleAnalysisCache default path for those official Microsoft supported PowerShell Windows container images so that anyone who is using it will know that they need to refer this documentation.

**Comment by TravisEz13** [comment]
Those docs are correct for Windows PowerShell.  The path for PowerShell Core is a hash of various things to make sure we don't conflict.  I'm using the variable to make the location fixed.  I can make it a fixed location relative to the original location. Perhaps `${env:LOCALAPPDATA}\Microsoft\Windows\PowerShell\docker\ModuleAnalysisCache`

**Comment by TravisEz13** [comment]
I made the change, mainly because it's more appropriate location for the cache.  Honestly, I just put an arbitrary location to get the code working.

**Comment by kiazhi** [comment]
LGTM @TravisEz13

**Pull request merged**
