### PR TITLE
MCR is the defacto source for images

### PR DESCRIPTION
**Pull request by lantrix**
## PR Summary

As seen on the docker hub Powershell page and as per [other blog posts](https://techcommunity.microsoft.com/t5/Containers/Windows-Server-2019-Now-Available/ba-p/382430), MCR is the defect registry for images. Otherwise this doesn't align with all the other doco, including the docker hub page which links here.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `Dockerfile`, `.sh`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **Adds a new image or tag**
  - [x] Not Applicable
- **OR**
  - [ ] Update [README.powershellcommunity.md](https://github.com/PowerShell/PowerShell-Docker/blob/master/assets/README.powershellcommunity.md)
  - [ ] Update [vsts-ci.yml](https://github.com/PowerShell/PowerShell-Docker/blob/master/vsts-ci.yml)

### CODE REVIEW

**Comment by RDIL** [comment]
Hello @msftbot!  Please if possible stop repeating yourself! 😉 
- my email

**Comment by TravisEz13** [comment]
@RDIL... I can turn the message off, but new contributors like @lantrix may not know what the tag means and the instructions are useful to me.

**Comment by lantrix** [comment]
Thanks @TravisEz13 now I know what it means :)

I think I made the assumption that commit 839ec89fb427ed7828aa82ad2b2af2812015bc96  updated the readme at https://hub.docker.com/_/microsoft-powershell but it's still got the old links.

**Comment by TravisEz13** [comment]
I'll have to redeploy the readme...  The mcr.microsoft.com system won't read directly from the repo

**Comment by TravisEz13** [comment]
I've created a PR to update the readme in MCR (and a PR to reflect back change from MCR.)   Please feel free to update the docs.  If you update either of those readmes, you should open a work item for the readmes to be updated in MCR.

**Pull request merged**
