### PR TITLE
Update ParrotSec commands

### PR DESCRIPTION
**Pull request by kiazhi**
## PR Summary

- Align with ParrotSec recommendations;
  - Replace `apt-get` with `apt`
  - Replace `apt-get dist-upgrade` with `parrot-upgrade`
  - Fix other miscellaneous minor item

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `Dockerfile`, `.sh`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **Adds a new image or tag**
  - [x] Not Applicable
- **OR**
  - [ ] Update [README.powershellcommunity.md](https://github.com/PowerShell/PowerShell-Docker/blob/master/assets/README.powershellcommunity.md)
  - [ ] Update [vsts-ci.yml](https://github.com/PowerShell/PowerShell-Docker/blob/master/vsts-ci.yml)

### CODE REVIEW

**Comment by kiazhi** [comment]
Honestly, this parrotsec build issue is not related to the committed code.

There seems to be a certificate chain issue from this `https://mirrors.mit.edu/` mirror repo url which is causing the problem in fetching packages. The Root CA certificate had expired since Sat, 30 May 2020 10:48:38 UTC (expired 4 days, 6 hours ago) using [SSL Server Test](https://www.ssllabs.com/ssltest/analyze.html?d=mirrors.mit.edu&hideResults=on)

```text
Subject: USERTrust RSA Certification Authority
Fingerprint SHA256: 1a5174980a294a528a110726d5855650266c48d9883bea692b67b6d726da98c5
Pin SHA256: x4QzPSC810K5/cMjb05Qm4k3Bw5zBn4lTdO/nEW/Td4=
Valid until: Sat, 30 May 2020 10:48:38 UTC (expired 4 days, 6 hours ago)   EXPIRED
Key: RSA 4096 bits (e 65537)
Issuer: AddTrust External CA Root
Signature algorithm: SHA384withRSA
```

Any advise on what I should do? 🤔

**Comment by RDIL** [comment]
We should most likely ping somebody at MIT

**Comment by kiazhi** [comment]
> We should most likely ping somebody at MIT

Looks like they have finally updated their Root CA certificate in the certificate chain.

```text
Subject: USERTrust RSA Certification Authority
Fingerprint SHA256: 68b9c761219a5b1f0131784474665db61bbdb109e00f05ca9f74244ee5f5f52b
Pin SHA256: x4QzPSC810K5/cMjb05Qm4k3Bw5zBn4lTdO/nEW/Td4=
Valid until: Sun, 31 Dec 2028 23:59:59 UTC (expires in 8 years and 6 months)
Key: RSA 4096 bits (e 65537)
Issuer: AAA Certificate Services
Signature algorithm: SHA384withRSA
```

@RDIL, can you get @PoshChan bot to re-run CI? Thank you. If it works after this re-run, you can also do same with PRs containing parrotsec build fail issue.

**Comment by RDIL** [comment]
@poshchan please retry CI

**Comment by PoshChan** [comment]
@RDIL, successfully started retry of `docker-PR`

**Comment by TravisEz13** [comment]
@kiazhi  or @RDIL  Please feel free to submit a PR to give @kiazhi  permission to retry is own PRs.

**Pull request merged**
