### PR TITLE
Update Dockerfile for arm image

### PR DESCRIPTION
**Pull request by DanielSSilva**
Updated Dockerfile to the latest release

## PR Checklist

- [ X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [X ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [X ] [Make sure all `Dockerfile`, `.sh`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **Adds a new image or tag**
  - [x] Not Applicable
- **OR**
  - [ ] Update [README.powershellcommunity.md](https://github.com/PowerShell/PowerShell-Docker/blob/master/assets/README.powershellcommunity.md)
  - [ ] Update [vsts-ci.yml](https://github.com/PowerShell/PowerShell-Docker/blob/master/vsts-ci.yml)

### CODE REVIEW

**Comment by DanielSSilva** [comment]
Right. I just followed the same PR logic done here #121 
Although it's not currently being built, shouldn't it be good to keep up to date?

**Comment by TravisEz13** [comment]
This isn't about image build resuming. No one has ever integrated this image into the build system.

**Comment by RDIL** [comment]
Then... remove it?

**Comment by DanielSSilva** [comment]
Well, I'm sorry for the confusion then. Maybe it's better to close it

**Comment by TravisEz13** [comment]
@RDIL Please file an issue to add the image to the build system.  
@DanielSSilva No, we will take the change.  It is simple enough.

**Comment by TravisEz13** [comment]
@PoshChan Please remind me in 24 hours.

**Comment by PoshChan** [comment]
@TravisEz13, will remind you in 24 hours.

**Comment by PoshChan** [comment]
@TravisEz13, this is the reminder you requested 24 hours. ago

**Pull request merged**
