### PR TITLE
Update node to v14

### PR DESCRIPTION
**Pull request by RDIL**
Signed-off-by: Reece Dunham <me@rdil.rocks>

## PR Summary

Node 10 goes EOL soon and dependabot keeps bugging everybody about this so I think its time to update.  

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `Dockerfile`, `.sh`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **Adds a new image or tag**
  - [ ] Not Applicable
- **OR**
  - [ ] Update [README.powershellcommunity.md](https://github.com/PowerShell/PowerShell-Docker/blob/master/assets/README.powershellcommunity.md)
  - [x] Update [vsts-ci.yml](https://github.com/PowerShell/PowerShell-Docker/blob/master/vsts-ci.yml)

### CODE REVIEW

**Comment by TravisEz13** [comment]
unfortunately this increased the image sizes...

**Comment by TravisEz13** [comment]
Actually these aren't supported by azure dev ops... that was our primary scenario...

**Comment by TravisEz13** [comment]
and I think the depended on node 10...

**Comment by RDIL** [comment]
@TravisEz13 what depends on node 10?

**Comment by TravisEz13** [comment]
Azure DevOps had a specific node version dependency.

**Comment by RDIL** [comment]
Well how can we test this then because this version of node 10 not only has high severity vulnerabilities but is also about to be EOL'd.

**Comment by TravisEz13** [comment]
We have to build and delpoy them to test...

**Comment by TravisEz13** [comment]
Here are the current requirements docs:  https://docs.microsoft.com/en-us/azure/devops/pipelines/process/container-phases?view=azure-devops

**Comment by TravisEz13** [comment]
let's merge.

**Pull request merged**
