### PR TITLE
Add debian test-dep image

### PR DESCRIPTION
**Pull request by TravisEz13**
## PR Summary

Add debian test-dep image
  - Also, add more tests to verify test dependencies are there
  - Also, add more tests to verify that base image utilities are there

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `Dockerfile`, `.sh`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **Adds a new image or tag**
  - [ ] Not Applicable
- **OR**
  - [ ] Update [README.powershellcommunity.md](https://github.com/PowerShell/PowerShell-Docker/blob/master/assets/README.powershellcommunity.md)
  - [ ] Update [vsts-ci.yml](https://github.com/PowerShell/PowerShell-Docker/blob/master/vsts-ci.yml)

### CODE REVIEW

**Comment by TravisEz13** [comment]
@RDIL  I expect some of the tests I added will fail on existing images.  I'll adjust the tests and/or images once I find out what the failures are.

**Comment by RDIL** [comment]
I'll keep an eye out

**Comment by RDIL** [comment]
@TravisEz13 nanoserver broke

**Comment by TravisEz13** [comment]
@RDIL It's an agent issue.  I'll retry the job once the CI finishes.

**Comment by RDIL** [comment]
winservercore also failed

**Comment by TravisEz13** [comment]
that is a logic error, already, copied the fix from another test.

**Comment by TravisEz13** [comment]
fix pushed as the last, test gave me all the information it could, none of the linux images failed, so no other test adjustments should be needed.

**Pull request merged**
