### PR TITLE
Add Fedora 28 and Fedora 27 image definitions.

### PR DESCRIPTION
**Pull request by adelton**
This is basically a copy of `Dockerfile`s from https://github.com/PowerShell/PowerShell/pull/6963.

### CODE REVIEW

**Comment by adelton** [comment]
I did not include other files found in `release/centos7`:

* `getLatestTag.ps1` talks about `xenial` in comment;
* `psVersions.json` and `tags.json` seem to be the same across `centos7` and `ubuntu*` directories ... so they should not be duplicated in the first place.

It it's critical that these files are in Fedora subdirectories as well, I can of course add copy there as well.

**Comment by TravisEz13** [comment]
The other files are used to automate our builds.  I'm going to add them...  hopefully in the next hour.

**Comment by TravisEz13** [comment]
I only put the Fedora 28 image in the preview folder.  @adelton  Could you add a readme.md either in this or after this PR explaining that Fedora 28 is only supported in DotNet 2.1 and there for only PowerShell 6.1?

**Comment by TravisEz13** [comment]
@adelton CI now passes.  fedora is taking 10 minutes to build.  Perhaps we should consider splitting up the builds some other way, but we shouldn't hold up your PR for this.  I only made minimal changes to your docker files, all of which are contained within this commit:  https://github.com/PowerShell/PowerShell-Docker/pull/8/commits/361274516d5231db8b64669690db5c54e1211fc8

We normally give 24 hours for review, but with the weekend starting.  I'm going to merge.  Feel free to still comment on my changes.  

The tags.json is the tag format for the image.

The psVersions.json is the version of powershell we will build an image for.

getLatestTag.ps1  returns a structure telling us a tag to build from and how to represent that tag in the tag template.  Here are the properties of the structure:

| Name | description |
|-------|------------|
| Tag     | What we should tag the image |
| Type   | Full or short.  Some images have two representations of the same tag.  A full descriptive tag, and short.  Just say which one the 'Tag' property is.  For example for xenial, a short tag would be `xenial` and a long tag would be `xenial-20180525`.|
| FromTag | the tag we should build the image from.  We should try to use the most descriptive tag.  For example for ubuntu, I would use `xenial-20180525` |

**Comment by TravisEz13** [comment]
@adelton  Thanks for your contribution.

**Comment by adelton** [comment]
Thank you.

**Comment by TravisEz13** [comment]
I filed https://github.com/PowerShell/PowerShell-Docker/issues/9 to document the files and fields I started documenting above.

**Pull request merged**
