### PR TITLE
Add libraries needed for NTLM to centos images

### LINKED ISSUE #124: Including support for NTLM for the microsoft/docker container
As per PowerShell/PowerShell#8817, the `microsoft/docker` container does not support NTLM which makes it pretty limited against what you can invoke WinRM with. I was under the assumption that NTLM would be implemented as part of PowerShell or at the very least be included as part of the container.

As per the blogpost at https://blog.quickbreach.io/ps-remote-from-linux-to-windows/, the container at https://hub.docker.com/r/quickbreach/powershell-ntlm/ includes the gssapi library that you need to include in order to include NTLM support.

##

Status

- [x] Evaluate other image
- [ ] stable images
  - [x] CentOs7
  - [x] Ubuntu Images
  - [x] Debian Images
  - [x] Fedora Images
  - [ ] Alpine
  - [ ] openSUSE
- [ ] preview images
  - [x] CentOs7
  - [x] Ubuntu Images
  - [x] Debian Images
  - [x] Fedora Images
  - [ ] Alpine
  - [ ] openSUSE
- [ ] All Community Stable Images

FYI, there are no plan to do functional validation for this.

Our efforts currently are focusing on SSH remoting.

### PR DESCRIPTION
**Pull request by RDIL**
## PR Summary

from #124 

edit: failures seem unrelated to this change
## PR Checklist

please don't make me fill this out 🐙 

cc @TravisEz13

### CODE REVIEW

**Comment by TravisEz13** [comment]
@kiazhi 	FYI, arch and blackarch are hanging.

**Comment by RDIL** [comment]
:0 so many optimizations

**Comment by TravisEz13** [comment]
@RDIL 	really just two... I just didn't clone the repo... and the online editor isn't great.

**Comment by RDIL** [comment]
true, just a lot of commits and from the mobile view its hard to see real amounts

**Comment by TravisEz13** [comment]
@kiazhi 	FYI, I opened #126 for the non-responsive build

**Comment by RDIL** [comment]
should I rebase from your branch?

**Comment by TravisEz13** [comment]
@RDIL 	no, don't worry about it. 
The jobs are separate so I can force the merge.. so something.  I'll figure it out.

**Comment by RDIL** [comment]
okay 
what do you mean `so something`

**Comment by TravisEz13** [comment]
I meant `or something`

**Comment by RDIL** [comment]
oh ok
ill stop asking questions now sorry for being annoying

**Comment by TravisEz13** [comment]
no worries. See the other PR didn't fix the issue.  I had to tell the CI system to ignore the errors for arch and blackarch.  I'll file an issue.

I'll do small fixes for community images, but ultimately it's up to the community to keep them working.

**Pull request merged**
